export const START_CHARACTER_MODAL = 'START_OPEN_CHARACTER';
export const SUCCESS_CHARACTER_MODAL = 'SUCCESS_CHARACTER_MODAL';
export const ERROR_CHARACTER_MODAL = 'ERROR_CHARACTER_MODAL';

export const START_EPISODE_MODAL = 'START_OPEN_EPISODE';
export const SUCCESS_EPISODE_MODAL = 'SUCCESS_EPISODE_MODAL';
export const ERROR_EPISODE_MODAL = 'ERROR_EPISODE_MODAL';